name: "Release"
on: 
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test GA Workflow
      run: |
        echo "Hello World!"